#vim: set ft=yml sw=2 ts=2 sts=2 et tw=78

version: '3'
services:

       
  elastic:
     image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
     container_name: dengue_elasticsearch
     ports:
      - 9250:9200
      - 9350:9300
     environment:
       ELASTIC_PASSWORD: Cds.2016
       NETWORK_HOST: 0.0.0.0
     
  #
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    container_name: dengue_kibana_1
    environment:
      SERVER_NAME: kibana.dengue
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: Cds.2016
      ELASTICSEARCH_URL: http://elastic:9250
      SERVER_HOST: 0.0.0.0
    ports:
      - 5610:5601
    

      
  #Work as urls filter and redirect to api implement acces control to key-set 
  nginx:
    build: ./nginx
    command: [nginx-debug, '-g', 'daemon off;']
    container_name: dengue_nginx
    ports:
     - "86:80"
     - 5612:5612
    network_mode: "host"    



networks:
  toexternal:
    # Use a custom driver
    driver: host

