FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
MAINTAINER Nelson Duranona <nelsonds.py@gmail.com>
#ADD ./config/jvm.options /usr/share/elasticsearch/config/
#ADD ./config/elasticsearch.yml /usr/share/elasticsearch/config/
#USER root
#RUN chown elasticsearch:elasticsearch ./config/jvm.options ./config/elasticsearch.yml

USER elasticsearch

EXPOSE 9200 9300
